### ISSUE TITLE
Notifications not marked as read on clicking

### ISSUE THREAD

**Issue by Mazikins** [porowns/kryptedauth#21]
When new notifications are created, clicking on them from the notification bubble will not mark them as read, instead the user has to click on the "View All" option.

Steps to reproduce:
1. Go to http://dev.kryptedgaming.com/games/
2. Next to Eve Online, click the "+" and "x" symbols several times
3. New notifications will be created for the user adding and removing a game to/from their account.
4. Click on the new notification icon at the top left of the screen, which will expand the list of unread notifications.
5. Click on any notification in the list.
6. Notice that the number of unread notifications remains the same and the list does not become smaller.

**Comment by porowns** [comment]
Will need to make an AJAX call on the button press of notifications.
