### ISSUE TITLE
UnboundLocalError at /applications/create/eve/

### ISSUE THREAD

**Issue by pstatonvt** [porowns/kryptedauth#23]
When applying for a 'guild' for Eve Online, once you click the 'Apply' button it takes you to this image:
![capture](https://user-images.githubusercontent.com/30532152/35393074-85dd3a0a-01a9-11e8-9045-2a972bcb3ca0.PNG)

**Comment by porowns** [comment]
Note: Currently working on fix for multiple corporations, since originally guilds only support one in-game group.

**Comment by porowns** [comment]
Issue has been resolved, problem was application template not existing in database.
