### ISSUE TITLE
Some special characters break the profile page

### ISSUE THREAD

**Issue by Mazikins** [porowns/kryptedauth#25]
http://dpaste.com/3KFJN9T

I copy/pasted the Icelandic alphabet in the "About Me" section of the user profile, specifically this part:

http://dpaste.com/3KFJN9T

Aa | a | [aː] | 10.11%
-- | -- | -- | --
Áá | á | [äu̯] | 1.8%
Bb | bé | [pjeɛ̯] | 1.04%
Dd | dé | [tjeɛ̯] | 1.58%
Ðð | eð | [eɛ̯ð̠] | 4.39%
Ee | e | [eɛ̯] | 6.42%
Éé | é | [jeɛ̯] | 0.65%
Ff | eff | [ɛfː] | 3.01%
Gg | ge | [ceɛ̯] | 4.24%
Hh | há | [häu̯] | 1.87%
Ii | i | [ɪː] | 7.58%
Íí | í | [iː] | 1.57%
Jj | joð | [joɔ̯ð̠] | 1.14%
Kk | ká | [kʰäu̯] | 3.31%
Ll | ell | [ɛtːl̥] | 4.53%
Mm | emm | [ɛmː] | 4.04%
Nn | enn | [ɛnː] | 7.71%
Oo | o | [oɔ̯] | 2.17%
Óó | ó | [ou̯] | 0.99%
Pp | pé | [pʰjeɛ̯] | 0.79%
Rr | err | [ɛrː] | 8.58%
Ss | ess | [ɛsː] | 5.63%
Tt | té | [tʰjeɛ̯] | 4.95%
Uu | u | [ʏː] | 4.56%
Úú | ú | [uː] | 0.61%
Vv | vaff | [vafː] | 2.44%
Xx | ex | [ɛxs] | 0.05%
Yy | ufsilon y | [ˈʏfsɪlɔn ɪː] | 0.9%
Ýý | ufsilon ý | [ˈʏfsɪlɔn iː] | 0.23%
Þþ | þorn | [θ̠ɔrtn̥] | 1.45%
Ææ | æ | [ai̯] | 0.87%
Öö | ö | [œː] | 0.78%

**Comment by porowns** [comment]
Note: Unicode is solution https://thejimmyg.github.io/pylonsbook/en/1.1/unicode.html
